---
- hosts: buildservers
  roles:
    - git
    - jq
    - nuget.commandline
    - dotnet4.5
    - visualstudio2017buildtools
    - nunit
    - python
    - nodejs
    - dotnet4.7.2
    - vscode
    - vscode-java-test