stages:
  - python-test
  - build-package

python-test:
  image: python:3.10-slim-bullseye
  stage: python-test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - apt-get update
    - apt-get install -y dialog apt-utils
    - apt-get install -y curl
    - apt-get install -y gnupg
    - apt-get install -y gnupg1
    - apt-get install -y gnupg2
    - apt-get install -y g++ unixodbc-dev
    - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    - curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
    - apt-get update
    - ACCEPT_EULA=Y apt-get install -y msodbcsql17
    - pip3 install -r requirements.txt
    - pip3 install pytest pytest-cov
    - coverage run -m pytest --junitxml=report.xml unittests/*
    - coverage report --omit=unittests/*
    - coverage xml --omit=unittests/*
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

build-package:
  stage: build-package
  image: python:3.10-slim-bullseye
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository gitlab dist/* --config-file /tmp/.pypirc --verbose