---
- name: Update GitLab Runner Agent on Linux
  shell: |
    sudo gitlab-runner stop
    sudo curl -L --output /usr/local/bin/gitlab-runner "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
    sudo chmod +x /usr/local/bin/gitlab-runner
    sudo gitlab-runner start
