---
- name: Download the GitLab Runner binary
  win_get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-windows-amd64.exe
    dest: C:\temp\gitlab-runner-windows-amd64.exe
    force: yes

- name: Ensure the GitLab Runner service is stopped
  win_shell: |
    cd C:\GitLab-Runner
    .\gitlab-runner-windows-amd64.exe stop

- name: Replace the runner's executable and start the service
  win_shell: |
    xcopy /y /s C:\temp\gitlab-runner-windows-amd64.exe C:\GitLab-Runner
    cd C:\GitLab-Runner
    .\gitlab-runner-windows-amd64.exe start
